core/app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/**
 * USER AUTHENTICATION MIDDLEWARE
 */
Route::group(['middleware' => ['auth']], function()
{
    Route::get('/', [
        'as' => 'index', 'uses' => 'WelcomeController@admin'
    ]);

    Route::get('/getSalesCap', [
        'as' => 'index', 'uses' => 'WelcomeController@getSalesCap'
    ]);
});

Route::get('user/login', [
    'as' => 'user.login', 'uses' => 'AuthController@loginView'
]);

Route::post('user/login', [
    'as' => 'user.login', 'uses' => 'AuthController@login'
]);

Route::get('user/logout', [
    'as' => 'user.logout', 'uses' => 'AuthController@logout'
]);

Route::get('test/test', 'WelcomeController@test'); //This is test controller to test data...

//add columns to all table
Route::get('get_all_table_in_db', function(){
	$test = DB::select('
		SELECT * FROM information_schema.tables WHERE table_schema = "ecommerce" 
	');

	foreach ($test as $key => $value) {
		DB::select('
			ALTER TABLE '.$value->TABLE_NAME.' ADD COLUMN `status` INT DEFAULT 1 NOT NULL,
			ADD COLUMN `created_at` DATETIME NOT NULL,
			ADD COLUMN `updated_at` DATETIME NULL,
			ADD COLUMN `deleted_at` DATETIME NULL;
		');
	}
});

Route::group(['prefix' => 'api'], function ()
{
    Route::any('getCustomerOrder/{id}', 'ApiController@getCustomerOrder');

    Route::any('getCategoryHierarchy/{type_id}', 'ApiController@getCategoryHierarchy');

    Route::any('getCategoryChildren/{cat_id}', 'ApiController@getCategoryChildren');

    Route::any('getAllProducts', 'ApiController@getAllProducts');

    Route::any('getProductsByCategoryId/{cat_id}', 'ApiController@getProductsByCategoryId');
});

core/app/Models/User.php
<?php namespace App\Models;

//use Illuminate\Database\Eloquent\Model;
use Cartalyst\Sentinel\Users\EloquentUser as CartalystUser;

/**
 * User Model Class
 *
 *
 * @category   Models
 * @package    Model
 * @author     Yasith Samarawickrama <yazith11@gmail.com>
 * @copyright  Copyright (c) 2015, Yasith Samarawickrama
 * @version    v1.0.0
 */
class User extends CartalystUser{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['first_name', 'last_name', 'permissions', 'last_login', 'email', 'status', 'username', 'password'];

	/**
	 * Login column names
	 *
	 * @var array
	 */
	protected $loginNames = ['email', 'username'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password'];

	/**
	 * Get the full name of the User
	 *
	 * @return string  		Full Name
	 */
	public function getFullNameAttribute(){
		return $this->attributes['first_name'].' '.$this->attributes['last_name'];
	}
}

core/resources/views/includes/menu.blade.php
<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu">
	<!-- <li class="header">MAIN NAVIGATION</li> -->
	<hr>
@if(isset($menu))
	{!!$menu!!}
@endif
</ul>

core/resources/views/includes/notifications.blade.php
<li>
    <a href="javascript:;" data-toggle="dropdown">
      <i class="fa fa-bell-o"></i>
      <div class="status bg-danger border-danger animated bounce"></div>
    </a>
    <ul class="dropdown-menu notifications">
      <li class="notifications-header">
        <p class="text-muted small">You have 3 new messages</p>
      </li>
      <li>
        <ul class="notifications-list">
          <li>
            <a href="javascript:;">
              <span class="pull-left mt2 mr15">
                <img src="{{asset('assets/sammy_new/images/avatar.jpg')}}" class="avatar avatar-xs img-circle" alt="">
              </span>
              <div class="overflow-hidden">
                <span>Sean launched a new application</span>
                <span class="time">2 seconds ago</span>
              </div>
            </a>
          </li>
        </ul>
      </li>
      <li class="notifications-footer">
        <a href="javascript:;">See all messages</a>
      </li>
    </ul>
</li>

core/resources/views/includes/user.blade.php
<style type="text/css">
  .dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus {
    color: #D96557;
    text-decoration: none;
    background-color: #f5f5f5;
}

.dropdown-menu > li > a {
    display: block;
    padding: 5px 10px;
    clear: both;
    font-weight: normal;
    line-height: 1.42857143;
    color: #333;
    white-space: nowrap;
}

.dropdown-menu > li > a {
    padding-right: 15px;
    padding-left: 15px;
    color: #616161;
    font-size: 13px;
    
}



</style>
<li>
    <a href="javascript:;" data-toggle="dropdown">
      <img src="{{asset('assets/sammy_new/images/avatar.jpg')}}" class="header-avatar img-circle ml10" alt="user" title="user">
      <span class="pull-left">@if(isset($user)) {{{$user->full_name}}} @endif</span>
    </a>
    <ul class="dropdown-menu">
          <li style="padding-top: 5px;padding-left: 7px;padding-right: 7px;">
             <a href="javascript:;"><i class="fa fa-cog" style="width: 28px;"></i>Settings</a>
          </li>
          <li style="padding-top: 5px;padding-left: 7px;padding-right: 7px;">
            <a href="javascript:;"><i class="fa fa-info" style="width: 30px;"></i>Help</a>
          </li>
         <li style="padding-top: 5px;padding-left:7px;padding-right: 7px;padding-bottom: 5px;">
          <a href="{{{url('user/logout')}}}"><i class="fa fa-sign-out" style="width: 30px;"></i>Logout</a>
         </li>
    </ul>
</li>